version: '3'

services:
  db:
    build:
      context: ./docker/
      dockerfile: Dockerfile.db
    container_name: many_sales_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: many_sales
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: many_sales_phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_uSER: admin
      PMA_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

  web:
    build:
      context: ./docker/
      dockerfile: Dockerfile.web
    restart: always
    container_name: many_sales_app
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db

