FROM php:7.3-apache

# Instalar dependências
RUN apt-get update && apt-get install -y \
    libzip-dev \
    mariadb-client \
    && docker-php-ext-install zip mysqli pdo_mysql

# Instalar o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Instalar os pacotes necessarios
RUN composer install

# Configurar Apache
RUN a2enmod rewrite

# Copiar arquivos
COPY . /var/www/html

# Configurar permissões do projeto
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html