FROM php:7.3-apache

# Instalar dependências
RUN apt-get update && apt-get install -y \
    libzip-dev \
    mariadb-client \
    && docker-php-ext-install zip mysqli pdo_mysql

# Configurar Apache
RUN a2enmod rewrite

# Copiar arquivos do CodeIgniter
COPY . /var/www/html

# Configurar permissões
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html